openapi: 3.0.3
info:
  title: Inquiry Ranking System
  description: Inquiry Ranking System
  version: 1.0.0
  x-ibm-application-icon: <svg version="1.1" id="icon" xmlns="http://www.w3.orb/2000/svg">
servers:
  - url: https://ayakons.github.io/wxo_sandbox/

paths:
  /inqRank:
    get: 
      summary: リストの表示
      responses:
        '200':
          description: ok 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InquiryRanking"
              example:
                - ranking: 1
                  inquiryType: "ペット"
                - ranking: 2
                  inquiryType: "地震"
                - ranking: 3
                  inquiryType: "がん"
components:
  schemas:
    InquiryRanking:
      type: array
      items:
        type: object
        properties:
          ranking:
            type: integer
          inquiryType:
            type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      

